kgshank/gse-sound-output-device-chooser

sound-output-device-chooser@kgshank.net/base.js
Hey, I love this extension but 1 small issue bugged me. 
if you have no input devices connected (no mic), the extension will show 'Extension initializing..." forever (where the input-device chooser should be).
So I fixed it here by automatically hiding the device-chooser if there are currently 0 known devices.
Feel free to comment me if I did this fix in a bad way and you would do it differently.
from my commit msg: 
> updated _setVisibility to show the device chooser only when atleast 1 device found, otherwise it will be hidden.
> also updated _deviceAdded and _deviceRemoved to invoke '_setVisibility' hide/show when number of devices changes
=> auto hide device-chooser when there are no devices

sound-output-device-chooser@kgshank.net/metadata.json
Even if the last commit fixed compatibility with 3.32, I believe compatibility has to be stated in the metadata for it to be installable through the extensions store.
=> Update compatible version

sound-output-device-chooser@kgshank.net/base.js
Fixes https://github.com/kgshank/gse-sound-output-device-chooser/issues/42
The pulseaudio equalizer sink has a null port so it's not initialized as the current sink at starup. This commit introduces a conservative fix: allow null ports only if both the stream port and the uidevice port is null.
=> Detect streams with null port at initialization

sound-output-device-chooser@kgshank.net/utils/libpulse_introspect.py
Fixes #79 and also makes it work on Fedora 31.
=> Locate libpulse library by name instead of loading by hardcoded path.

sound-output-device-chooser@kgshank.net/metadata.json
=> Update metadata.json to include Gnome 3.38

sound-output-device-chooser@kgshank.net/base.js
This prevents calling a C function with an old pointer from the JS
timeout callback which then crashes the GNOME Shell.
An upstream fix was also sent in which prevents the crash of GNOME
Shell but still this bug here needs to be fixed.
Fixes #110 #108
=> Delete reference to removed object

sound-output-device-chooser@kgshank.net/convenience.js, sound-output-device-chooser@kgshank.net/prefs.js
For each port, retrieves the corresponding card and uses `card_description` to build port display name.
Port name should now be the same as in gnome sound settings
=> 🐛 fixes `undefined` in name in port-settings

Makefile, sound-output-device-chooser@kgshank.net/ui/prefs-dialog40.glade
This PR upgrades glade and prefs panel to GTK 4.0, which is the major version required by GNOME 40. This change is not backward  compatible, due to this issue I have removed old versions of GNOME from the metadata.json file.
Note that you can support multiple versions of your awesome extensions uploading one version for each GNOME versions you want to support to extensions.gnome.org.
If you find any issue with this PR no not hesitate to contact me.
=> Add support for GNOME 40

Makefile
The build action will never trigger, because it matches a filename. Marking all your make actions as .PHONY is the correct course of action.
=> Make actions should be marked phony

sound-output-device-chooser@kgshank.net/base.js
This patch should fix the issue #163 .
Now the refresh of active profiles is event-signal driven from signal emitted from submenu when it opens ("open-state-changed").
Added method `_onSubmenuOpenStateChanged()` which is called when  "open-state-changed" in order to give some future-proof (if we need something else to be called when submenu opens in the future).
Indeed I call `_setActiveProfile()` without checking if `Prefs.SHOW_PROFILES` is true, this doesn't create a problem. I thought that adding a variable that will keep track of the state of the pref will get things bloated while checking the actual `Prefs.SHOW_PROFILES` every time we open the submenu might not be a good idea from a performance standpoint (i dont really know).
Let me know if I should add a check for …
=> Fix issue #163 (Change profiles refresh from timer to event-signal system)

sound-output-device-chooser@kgshank.net/extension.js
More less the title...
If you disable the extension while the slider integration is enabled gnome-shell "losses" its volume slider.
This small 3 lines patch fix that.
Thank you and have a nice day :)
=> Fix bug when disabling extension while slider integration is enabled

sound-output-device-chooser@kgshank.net/base.js, sound-output-device-chooser@kgshank.net/convenience.js, sound-output-device-chooser@kgshank.net/extension.js
From my understanding we want to be safe from an `actor` getter drop in a feature gnome-shell release.
This commit extent the idea of `getActor` in order to provide better support for gnome-shell 3.32 while also keeping safe from a drop of `actor` getter in a future gnome-shell release.
Should also fix #205 .
=> getActor() globally for 3.32 compatibility

README.md
The command as-is quotes the asterisk, so it attempts to remove a directory with literal asterisks in it.
```
$ echo rm -rf "*sound-output-device-chooser*"
rm -rf *sound-output-device-chooser*
$ echo rm -rf *sound-output-device-chooser*
rm -rf gse-sound-output-device-chooser sound-output-device-chooser@kgshank.net
```
=> Fix installation rm instructions

sound-output-device-chooser@kgshank.net/base.js
It looks like 2eee4716deeb6b995ec29cc5855879e17c6847f3 intended to fix this, but is not sufficient when "Hide selector if there's only one device" is off (the default).
See #195, #121
Before fix:
After fix:
=> Fix "Extension initialising..." when there are no devices

sound-output-device-chooser@kgshank.net/metadata.json
Tested on Ubuntu Jammy Jellyfish + GNOME PPA with gnome-shell 42~alpha.
Preferences works too.
Thanks for this nice and useful extension.
=> Add 42 since it works there too

sound-output-device-chooser@kgshank.net/base.js
According to
https://gjs.guide/guides/gobject/subclassing.html#subclassing-gobject,
Javascript classes that subclass GObject must implement an _init()
initializer instead of using a regular constructor.  The ProfileMenuItem
and SoundDeviceMenuItem each subclass PopupMenu classes that ultimately
subclass a GObject class.
This has just worked because the constructor itself was called, and it
in turn was calling the correct _init methods.  gjs commit 16032db6cd2
(Correctly chain constructor prototypes to enable static inheritance)
made it so that constructors are called directly but the gjs
behavior of calling _init still occurs.  It occurs using this._init(),
though so what has happened is as follows.
SoundDeviceChooserBase._deviceAdded instantiates a SoundDeviceMenuItem
with four arguments …
=> Properly fix for GNOME 42 / gjs 1.72.0 (#229).

sound-output-device-chooser@kgshank.net/extension.js
Tested it also on Gnome 3.36, doesn't brake old style.
Sad it that for few hour this fix might won't make it to next release.
// rant...
Personally I believe that we should push next releases with "Integrate selector with slider". Ofc, I am biased since I pushed for that integration. However I do believe that it look better and we should push it for new user by default (and ofc keeping the options to disable it). Should note that I daily drive it with enabled (if that proves some robustness). Maybe make a poll, idk.
=> Style fix for Gnome 42 "Integrate selector with slider"

sound-output-device-chooser@kgshank.net/base.js
Device names are usually required when port names are not enough to distinguish audio ports. This commit puts the device name first, so it's much easier to visually find the desired port
=> Show device name before the input name

Makefile, README.md, sound-output-device-chooser@kgshank.net/metadata.json
Added Gnome "43" to the support "shell-version" in the metadata.json.
Also added two Makefile tasks to quickly enable/disable the plugin for local testing.
Tested this change quickly with Fedora 37 with Gnome 43.2 (and X11) and the plugin works still fine.
=> Add support for Gnome 43

sound-output-device-chooser@kgshank.net/base.js
Removes dummy inputs/outputs created by [JamesDSP](https://github.com/Audio4Linux/JDSP4Linux) and [EasyEffects](https://github.com/wwmm/easyeffects) that aren't meant to be selected.
Solves #216
=> Hide JamesDSP & EasyEffects Sinks/Sources from selectors.

sound-output-device-chooser@kgshank.net/extension.js, sound-output-device-chooser@kgshank.net/schemas/org.gnome.shell.extensions.sound-output-device-chooser.gschema.xml
I responded to this #215 and decided I might as well implement it.
`Super + Alt + Page up/down` for output devices 
`Super + Alt + Home/End` for input devices
=> Implemented keyboard shortcuts for cycling input and output devices
